# Defining it here so that the scraper's file does not become so big, because
# that would bring readability issues.
ALLOWED_TOPICS = [
    "World & Nation",
    "California",
    "Politics",
    "Entertainment & Arts",
    "Opinion",
    "Sports",
    "Archives",
    "Business",
    "Travel & Experiences",
    "Movies",
    "Books",
    "Babylon & Beyond",
    "Science & Medicine",
    "World Now",
    "Television",
    "Food",
    "Music",
    "High School Sports",
    "2024 Paris Olympics",
    "Obituaries",
    "Technology and the Internet",
    "Opinion L.A.",
    "Soccer",
    "Top of the Ticket",
    "Letters to the Editor",
    "Culture Monster Blog",
    "Recipes",
    "Awards",
    "USC Sports",
    "Hollywood Inc.",
    "Autos",
    "Show Tracker",
    "Sports Now",
    "Lifestyle",
    "24 Frames",
    "Real Estate",
    "Varsity Times Insider",
    "Lakers",
    "The Big Picture",
    "For the Record",
    "Nation Now",
    "Jacket Copy",
    "Housing & Homelessness",
    "L.A. Unleashed",
    "Politi-Cal",
    "Dodgers",
    "Booster Shots",
    "Clippers",
    "Hockey",
    "L.A. Now",
    "Technology Blog",
    "Daily Dish",
    "La Plaza",
    "Company Town Blog",
    "De Los",
    "Readers Representative",
    "UCLA Sports",
    "All the Rage",
    "Money & Company",
    "Pop & Hiss",
    "Afterword",
    "Angels",
    "Climate & Environment",
    "L.A. at Home",
    "Ministry of Gossip",
    "Hero Complex Blog",
    "Olympics Blog",
    "Awards Tracker",
    "Company News",
    "L.A. Influential",
    "Los Angeles County Banking and Finance: Trends. Updates. Visionaries.",
    "About the Los Angeles Times",
    "Business of Law: Trends, Updates, Visionaries & In-House Counsel Leadership Awards",
    "Greenspace",
    "Image",
    "Los Angeles County Commercial Real Estate: Trends. Updates. Visionaries.",
    "Orange County",
    "Rams",
    "Updates",
    "Banking and Finance Trends, Updates and 2024 Visionaries",
    "Commercial Real Estate: Trends, Updates and Visionaries",
    "Dodgers Now",
    "Giving Back: Philanthropy Issue",
    "Podcasts",
    "Angel City FC",
    "Business of Law: Trends, Updates, Visionaries & The In-House Counsel Leadership Awards",
    "Business of Law Trends, Updates Visionaries and The In-House Counsel Awards Recap",
    "Entertainment Business Visionaries",
    "Inspirational Women: Trends. Updates. Forum and Leadership Awards",
    "Inspirational Women – Trends, Updates and the 2023 Forum and Leadership Awards",
    "The Homicide Report Blog",
]
